version: "3"
services:
  postgres:
    container_name: postgres
    image: "postgres:15"
    restart: always
    networks:
      project-network:
        ipv4_address: 192.168.41.4
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/conf:/etc/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  
  backend:
    container_name: backend
    build: .
    restart: always
    networks:
      project-network:
        ipv4_address: 192.168.41.2
    ports:
      - "9010:9010"
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    depends_on:
      postgres:
        condition: service_healthy

networks:
  project-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.41.0/24