version: "3"
services:
  postgres:
    container_name: postgres
    image: "postgres:15"
    restart: always
    networks:
      project-network:
        ipv4_address: 192.168.41.4
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/conf:/etc/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  
  backend:
    container_name: backend
    build:
      context: .
      network: host
      args:
        SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
    restart: always
    networks:
      project-network:
        ipv4_address: 192.168.41.2
    ports:
      - "9010:9010"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}

networks:
  project-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.41.0/24