name: Backend + DB Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-container:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Compose
        run: |
          POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          docker compose up --build -d