name: Backend + DB Run

on:
  push:
    branches:
      - DB-model
  pull_request:
    branches:
      - DB-model

jobs:
  run-container:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Compose
        run: |
          POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          SQLALCHEMY_DATABASE_URI=${{ secrets.SQLALCHEMY_DATABASE_URI }} \
          docker compose up --build postgres -d && docker compose up --build backend -d