name: Stack Run

on:
  push:
    branches:
      - feat_actions
  pull_request:
    branches:
      - feat_actions

jobs:
  run-container:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Compose
        run: docker-compose up --build postgres backend -d
