name: Trigger Backend Run Event

on:
  push:
    push:
      branches:
        - feat_actions
    pull_request:
      branches:
        - feat_actions

jobs:
  trigger:
    runs-on: ubuntu-22.04
    steps:
      - name: Repository Dispatch
        run: |
          curl -X POST \
              -H "Accept: application/vnd.github.everest-preview+json" \
              -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
              https://api.github.com/repos/Ingenieria-En-Software-2/stack/dispatches \
              -d '{"event_type":"backend-run"}'


